version: '3.8'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432" # 5433 to avoid conflicts with host postgres server
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data #DB data persisting


  servlet-api:
    build:
      context: ./servlet-api/
      dockerfile: Dockerfile
    ports:
      - "8089:8080"
    volumes:
      - ./servlet-api:/usr/src/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

  vue-web:
    build:
      context: ./vue
      dockerfile: Dockerfile
    volumes:
      - ./vue:/srv/app
      - vue-node_modules:/srv/app/node_modules
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: ${NODE_ENV}
      VITE_WEATHER_API_KEY: ${VITE_WEATHER_API_KEY}
      VITE_WEATHER_API_URL: ${VITE_WEATHER_API_URL}
    init: true
    stop_grace_period: 1s


volumes:
  postgres-data:
  vue-node_modules:

